config/routes.rb
Rails.application.routes.draw do
  root "categories#index"
  
  resources :categories do 
    resources :restaurants
  end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :restaurants, dependent: :destroy

	validates :name, presence: true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @restaurants = @category.restaurants
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to @category
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to root_path
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def show 
      @restaurant = Restaurant.find(params[:id])
  end

  def new
  	  @category = Category.find(params[:category_id])
      @restaurant = Restaurant.new
  end

  def create
  	  @category = Category.find(params[:category_id])
      @restaurant = @category.restaurants.create(restaurant_params)
      redirect_to category_path(@category)
  end

  def edit 
      @category = Category.find(params[:category_id])
      @restaurant = @category.restaurants.find(params[:id])
  end 

  def update
      @category = Category.find(params[:category_id])
      @restaurant = @category.restaurants.find(params[:id])
      @restaurant.update(restaurant_params)
      redirect_to category_path(@category) 
  end
         
  def destroy
      @category = Category.find(params[:category_id])
      @restaurant = @category.restaurants.find(params[:id])
      @restaurant.destroy
      redirect_to category_path(@category)
  end

  private
    def restaurant_params
      params.require(:restaurant).permit(:name, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/categories/_form.html.erb
<%= form_with model: category do |form| %>

  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% category.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<!DOCTYPE html>
<html>
<style>
body {background-color: powderblue;}
table, th, td {
  border:1px solid black;
}
</style>
<body>
  
<h1>Edit Category</h1>

<%= render "form", category: @category %> 

app/views/categories/index.html.erb
<!DOCTYPE html>
<html>
<style>
body {background-color: powderblue;}
table, th, td {
  border:1px solid black;
}
</style>
<body>

<h1 style="background-color:rgb(266, 167, 238);"><center>Category List</center></h1>
  <p>   
   <%= link_to 'Add Category', new_category_path %>   
  </p>    
<table style="width:100%">
  <tr>
    <th>Name</th>
    <th>Actions</th>
  </tr>
<tbody>   

       <% @categories.each do |category| %>   
          <tr>   
            <td><%= category.name %></td>        
               <div>   
               <td>   
                <%= link_to 'Show', category_path(category) %>   
                <%= link_to 'Edit', edit_category_path(category) %>   
                <%= link_to 'Delete', category_path(category), 
                       method: :delete,
                       data: { confirm: "Are you sure?" } %>   
              </div>   
            </td>   
          </tr>   
      <% end %>   
      </tbody>   
    </table>   
  </body> 
</html>     

app/views/categories/new.html.erb
<!DOCTYPE html>
<html>
<style>
body {background-color: powderblue;}
table, th, td {
  border:1px solid black;
}
</style>
<body>
	
<h1>New Category</h1>

<%= render "form", category: @category %>

app/views/categories/show.html.erb
<!DOCTYPE html>
<html>
<style>
body {background-color: powderblue;}
table, th, td {
  border:1px solid black;
}
</style>
<body>
<h1><%= @category.name %></h1>

<%= link_to "create restaurants",  new_category_restaurant_path(@category)%>

<style>
body {background-color: powderblue;}
table, th, td {
  border:1px solid black;
}
</style>
<body>
<table style="width:100%">
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Actions</th>
  </tr>
<tbody>   
      <% @restaurants.each do |restaurant| %>   
          <tr>   
            <td><%= restaurant.name %></td>   
            <td><%= restaurant.address %></td>
               <div>   
               <td>   
                <%= link_to 'Show',  category_restaurant_path(id: restaurant.id,category_id:@category.id) %>   
                <%= link_to 'Edit', edit_category_restaurant_path(id: restaurant.id,category_id:@category.id) %>   
                <%= link_to 'Delete', category_restaurant_path(id: restaurant.id,category_id:@category.id), 
                       method: :delete,
                       data: { confirm: "Are you sure?" } %>   
              </div>   
            </td>   
          </tr>   
      <% end %>   
      </tbody>   
    </table>   
  </body>   
</html>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yash</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_with model: restaurant,url: category_restaurants_path(@category),method: "post" do |form| %>
  
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
  	<%=form.label :address %><br>
  	<%= form.text_area :address %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<%= form_with model: @restaurant,url: category_restaurant_path(@category),method: "put" do |form| %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :address %><br>
    <%= form.text_area :address %> 
  </p>
  
  <p>
    <%= form.submit %>
  </p>
<% end %>

<!DOCTYPE html>
<html>
<style>
body {background-color: powderblue;}
table, th, td {
  border:1px solid black;

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render "form", restaurant: @restaurant %>  

<!DOCTYPE html>
<html>
<style>
body {background-color: powderblue;}
table, th, td {
  border:1px solid black;

app/views/restaurants/show.html.erb
<!DOCTYPE html>
<html>
<style>
body {background-color: powderblue;}
table, th, td {
  border:1px solid black;
}
</style>
<body>

<h1><%= @restaurant.name %></h1>
<p><%= @restaurant.address %></p>